# Generated by Django 4.2 on 2023-04-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_class_class_id_alter_class_class_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
