# Generated by Django 4.2 on 2023-04-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_course_credit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MajorPlan',
        ),
    ]
