# Generated by Django 4.2 on 2023-04-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_delete_majorplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['course']},
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_no',
        ),
    ]
