# Generated by Django 4.2 on 2023-04-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_class_end_class_start_alter_class_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='time',
            field=models.CharField(choices=[(1, '一'), (2, '二'), (3, '三'), (4, '四'), (5, '五')], default='一', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('teacher', 'time', 'start', 'end'), name='teacher_time'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('time', 'start', 'end', 'classroom'), name='time_classroom'),
        ),
        migrations.AddConstraint(
            model_name='courseselection',
            constraint=models.UniqueConstraint(fields=('student', 'class_field'), name='course_selection'),
        ),
    ]
