# Generated by Django 4.2 on 2023-04-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_class_time_class_teacher_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='current_selection',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='class',
            name='max_selection',
            field=models.IntegerField(default=50),
        ),
    ]
