# Generated by Django 4.2 on 2023-04-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_class_current_selection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='time',
            field=models.CharField(choices=[('一', '一'), ('二', '二'), ('三', '三'), ('四', '四'), ('五', '五')], default='一', max_length=10),
        ),
    ]
