# Generated by Django 4.2 on 2023-05-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_class_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
    ]
